Labs/LabFiles/Mod06/Starter/PhotoSharingApplication/src/PhotoSharingApplication/Models/Comment.cs
using System.ComponentModel.DataAnnotations;

namespace PhotoSharingApplication.Models
{
    public class Comment
    {
        public int Id { get; set; }
        public int PhotoId { get; set; }
        public string UserName { get; set; }
        [Required]
        [StringLength(250)]
        public string Subject { get; set; }
        [DataType(DataType.MultilineText)]
        public string Body { get; set; }
        public Photo Photo { get; set; }
    }
}

Labs/LabFiles/Mod06/Starter/PhotoSharingApplication/src/PhotoSharingApplication/Models/Photo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PhotoSharingApplication.Models
{
    public class Photo
    {
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        [Display(Name ="Picture")]
        public byte[] PhotoFile { get; set; }
        public string ImageMimeType { get; set; }
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
        [DataType(DataType.DateTime)]
        [Display(Name ="Created Date")]
        //[DisplayFormat(DataFormatString ="{0:MM/dd/yy")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yy}", ApplyFormatInEditMode = true)]
        public DateTime CreatedDate { get; set; }
        public string UserName { get; set; }
        public List<Comment> Comments { get; set; }
    }
}

Labs/LabFiles/Mod06/Starter/PhotoSharingApplication/src/PhotoSharingApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace PhotoSharingApplication.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

Labs/LabFiles/Mod06/Starter/PhotoSharingApplication/src/PhotoSharingApplication/Controllers/PhotosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PhotoSharingApplication.Data;
using PhotoSharingApplication.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using PhotoSharingApplication.ActionFilters;

namespace PhotoSharingApplication.Controllers
{
    [ServiceFilter(typeof(ValueReporter))]
    public class PhotosController : Controller
    {
        private PhotoSharingContext _context;
        public PhotosController(PhotoSharingContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View(nameof(PhotosController.Index));
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var photo = await _context.Photos.SingleOrDefaultAsync(m => m.Id == id);
            if (photo == null)
            {
                return NotFound();
            }

            return View(nameof(PhotosController.Details), photo);
        }

        // GET: Photos/Create
        public IActionResult Create()
        {
            Photo newPhoto = new Photo();
            newPhoto.CreatedDate = DateTime.Today;
            return View("Create", newPhoto);
        }

        // POST: Photos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CreatedDate,Description,ImageMimeType,Title,UserName")] Photo photo, IFormFile image)
        {
            photo.CreatedDate = DateTime.Today;
            if (!ModelState.IsValid)
            {
                return View(nameof(PhotosController.Create), photo);
            }
            else
            {
                if (image != null)
                {
                    photo.ImageMimeType = image.ContentType;
                    photo.PhotoFile = new byte[image.Length];
                    await image.OpenReadStream().ReadAsync(photo.PhotoFile, 0, (int)image.Length);
                }
                _context.Photos.Add(photo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(PhotosController.Index));
            }
        }

        // GET: Photos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var photo = await _context.Photos.SingleOrDefaultAsync(m => m.Id == id);
            if (photo == null)
            {
                return NotFound();
            }

            return View(photo);
        }

        // POST: Photos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var photo = await _context.Photos.SingleOrDefaultAsync(m => m.Id == id);
            _context.Photos.Remove(photo);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> GetImage(int id)
        {
            var photo = await _context.Photos.SingleOrDefaultAsync(m => m.Id == id);
            if (photo != null)
            {
                return File(photo.PhotoFile, photo.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

Labs/LabFiles/Mod06/Starter/PhotoSharingApplication/src/PhotoSharingApplication/ViewComponents/PhotoGalleryViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PhotoSharingApplication.Data;
using PhotoSharingApplication.Models;
using Microsoft.EntityFrameworkCore;

namespace PhotoSharingApplication.ViewComponents
{
    public class PhotoGalleryViewComponent : ViewComponent
    {
        private PhotoSharingContext _context;
        public PhotoGalleryViewComponent(PhotoSharingContext context)
        {
            this._context = context;
        }
        public async Task<IViewComponentResult> InvokeAsync(int number = 0) {
            List<Photo> photos;

            if (number == 0)
            {
                photos = await _context.Photos.ToListAsync();
            }
            else
            {
                photos = await (from p in _context.Photos
                          orderby p.CreatedDate descending
                          select p).Take(number).ToListAsync();
            }

            return View(photos);
        }
    }
}

Labs/LabFiles/Mod06/Starter/PhotoSharingApplication/src/PhotoSharingApplication/Views/Shared/Components/PhotoGallery/Default.cshtml
@model IEnumerable<PhotoSharingApplication.Models.Photo>

@foreach (var item in Model)
{
    <h3>"@item.Title"</h3>

    if (item.PhotoFile != null)
    {
        <img width="200" src="@Url.Action("GetImage", "Photos", new { id = item.Id })" />
    }

    <p>
        Created By:
        @Html.DisplayFor(model => item.UserName)
    </p>

    <p>
        Created On:
        @Html.DisplayFor(model => item.CreatedDate)
    </p>

    <a asp-action="Details" asp-controller="Photos" asp-route-id="@item.Id">Display</a> 

}

Labs/LabFiles/Mod06/Starter/PhotoSharingApplication/src/PhotoSharingApplication/Views/Shared/Components/PhotoGallery/View.cshtml
@model IEnumerable<PhotoSharingApplication.Models.Photo>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PhotoFile)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ImageMimeType)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreatedDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UserName)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhotoFile)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImageMimeType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>