Labs/LabFiles/Mod14/Starter/PhotoSharingApplication/src/PhotoSharingApplication/Controllers/CommentsController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PhotoSharingApplication.Models;
using PhotoSharingApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace PhotoSharingApplication.Controllers
{
    public class CommentsController : Controller
    {
        private ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IAuthorizationService _authorizationService;


        public CommentsController(ApplicationDbContext Context, UserManager<ApplicationUser> userManager, IAuthorizationService authorizationService)
        {
            _context = Context;
            _userManager = userManager;
            _authorizationService = authorizationService;
        }

        //POST: This action creates the comment when the AJAX comment create tool is used
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(Comment comment, int PhotoId)
        {
            comment.ApplicationUserId = _userManager.FindByNameAsync(User.Identity.Name).Result.Id;
            //Save the new comment
            _context.Comments.Add(comment);
            await _context.SaveChangesAsync();

            //Return the view component with the new list of comments
            return ViewComponent("CommentsForPhoto", new { PhotoId = PhotoId});
            
        }

        //
        // GET: /Comment/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int id = 0)
        {
            Comment comment = await _context.Comments
                .Include(c=>c.Photo)
                .ThenInclude(c=>c.Owner)
                .SingleOrDefaultAsync(c=>c.Id == id);
            if (comment == null)
                return NotFound();
            
            if (await _authorizationService.AuthorizeAsync(User, comment, "CommentDelete"))
            {
                ViewBag.PhotoId = comment.PhotoId;
                return View(comment);
            }
            else
                return Challenge();
        }

        //
        // POST: /Comment/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var comment = await _context.Comments.SingleOrDefaultAsync(c => c.Id == id);
            if (await _authorizationService.AuthorizeAsync(User, comment, "CommentDelete"))
            {
                _context.Comments.Remove(comment);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(PhotosController.Details), "Photos", new { id = comment.PhotoId });
            }
            else
                return Challenge();
        }
    }
}

Labs/LabFiles/Mod14/Starter/PhotoSharingApplication/src/PhotoSharingApplication/ViewComponents/CreateACommentViewComponent.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PhotoSharingApplication.Data;
using PhotoSharingApplication.Models;
using System.Threading.Tasks;

namespace PhotoSharingApplication.ViewComponents
{
    public class CreateACommentViewComponent : ViewComponent
    {
        private ApplicationDbContext _context;
        
        public CreateACommentViewComponent(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IViewComponentResult> InvokeAsync(int PhotoId)
        {
            //Create the new comment
            Comment newComment = new Comment();
            newComment.PhotoId = PhotoId;
            
            ViewBag.PhotoId = PhotoId;
            return View(newComment);
        }
    }
}

Labs/LabFiles/Mod14/Starter/PhotoSharingApplication/src/PhotoSharingApplication/Views/Shared/Components/CommentsForPhoto/Default.cshtml
@model IEnumerable<PhotoSharingApplication.Models.Comment>
@inject Microsoft.AspNetCore.Authorization.IAuthorizationService authorizationService
@inject SignInManager<ApplicationUser> SignInManager

<div id="comments-tool" class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Comments</h3>
    </div>
    <ul class="list-group" id="all-comments">
        @foreach (var item in Model)
        {
            <li class="list-group-item">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Owner.UserName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(modelItem => item.Owner.UserName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Subject)
                    </dt>

                    <dd>
                        @Html.DisplayFor(modelitem => item.Subject)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Body)
                    </dt>

                    <dd>
                        @Html.DisplayFor(modelitem => item.Body)
                    </dd>
                </dl>
                @if (await authorizationService.AuthorizeAsync(User, item, "CommentDelete"))
                {
                <a asp-action="Delete" asp-controller="Comments" asp-route-id="@item.Id" class="btn btn-info">
                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Delete This Comment
                </a>
                }
            </li>
        }
    </ul>
@if (SignInManager.IsSignedIn(User))
{
    <div id="addcomment" class="panel-footer">
        <form asp-controller="Comments" asp-action="Create" asp-route-photoId="@ViewBag.PhotoId" data-ajax="true" data-ajax-mode="replace" data-ajax-update="#comments-tool">
            <p>
                <vc:create-a-comment photo-id="@ViewBag.PhotoId"></vc:create-a-comment>
            </p>
        </form>        
    </div>
}
</div>